services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" 

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
    ports:
      - "8080:8080"
      - "8081:8081"
