version: "3.3"
services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - PROFILE=${PROFILE}
    ports:
      - "80:80" 

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}
    ports:
      - "8080:8080"
      - "8081:8081"
