version: "3.3"
services:
  frontend:
    build:
      context: ../Frontend
      dockerfile: Dockerfile_prod
      args:
        - PROFILE=dev
    ports:
      - "81:81"

  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile_prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8081"
