version: "3.3"
services:
  frontend_dev:
    container_name: fund_fusion_frontend_dev
    build:
      context: ../Frontend
      dockerfile: Dockerfile_dev
      args:
        - PROFILE=dev
    ports:
      - "80:80"

  backend_dev:
    container_name: fund_fusion_backend_dev
    build:
      context: ../Backend
      dockerfile: Dockerfile_dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
