version: "3.3"
services:
  frontend_prod:
    container_name: fund_fusion_frontend_prod
    build:
      context: ../Frontend
      dockerfile: Dockerfile_prod
      args:
        - PROFILE=dev
    ports:
      - "81:81"

  backend_prod:
    container_name: fund_fusion_backend_prod
    build:
      context: ../Backend
      dockerfile: Dockerfile_prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8081"
