spring:
  application:
    name: fundfusion

  datasource:
    url: jdbc:mysql://localhost:3306/fundfusion
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org:
      springframework: DEBUG
frontend:
  port: 5173

# Instructions for testing in a local environment:
# 1. Create a database named 'fundfusion' in your MySQL server.
# 2. Update the username and password fields with your MySQL credentials.
# 3. After successful testing, replace with the VM database credentials for deployment.
