spring:
  application:
  datasource:
    url: jdbc:mysql://db-5308.cs.dal.ca:3306/CSCI5308_5_DEVINT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: CSCI5308_5_DEVINT_USER
    password: Yi9phaech9
    initialization-mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: devpatel43543@gmail.com
    password: dfjragryfjtqnkwp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    #show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org:
      springframework:
        jdbd: DEBUG
      hibernate:
        SQL: DEBUG


#If you want to use some other database other than H2, just change the config accordingly. ## DO NOT COMMIT YOUR CHANGED FILE