name: Deploy to Dev

on:
  push:
    branches:
      - dev
      
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          PROFILE=dev docker-compose up --build --force-recreate -d


