name: Deploy to Server

on:
  push:
    branches:
      - main_ci_cd_test

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          PROFILE=prod docker-compose up --build --force-recreate -d


