name: Deploy to Server

on:
  push:
    branches:
      - dev
      
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          SPRING_PROFILE=dev docker-compose up -d
