name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          cd cicd && 
          docker-compose -f docker-compose-prod.yml up --build --force-recreate -d


